/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2021-02-23 14:10:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import dto.QuestionUserRelation;
import dto.QuestionAnswersRelation;
import dto.User;
import dto.Category;
import dao.CategoryDao;
import util.Constant;
import java.text.SimpleDateFormat;

public final class list_005fque_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.CategoryDao");
    _jspx_imports_classes.add("dto.User");
    _jspx_imports_classes.add("util.Constant");
    _jspx_imports_classes.add("dto.QuestionUserRelation");
    _jspx_imports_classes.add("dto.QuestionAnswersRelation");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("dto.Category");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>質問一覧 | Wisdom - Q＆A Communication</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=2.0,user-scalable=yes\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<link href=\"./jsp/wisdom.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script src=\"https://code.jquery.com/jquery-2.2.4.js\"></script>\r\n");
      out.write("\t\t<script src=\"./jsp/js/script.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<div id=\"loading\"></div>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<p class=\"img logo\"><a href=\"");
      out.print(Constant.PATH_WISDOM_CNTL);
      out.write("\"><img src=\"./jsp/images/wisdom_icon.png\" alt=\"Wisdom - Q＆A Communication\"></a></p>\r\n");
      out.write("\t\t\t\t<h1><a href=\"");
      out.print(Constant.PATH_WISDOM_CNTL);
      out.write("\">Wisdom - Q＆A Communication</a></h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<h1 class=\"balloon\">質問一覧</h1>\r\n");
      out.write("\t\t\t");
 @SuppressWarnings("unchecked")
			    ArrayList<QuestionUserRelation> questionUserRelations = (ArrayList<QuestionUserRelation>) request
			            .getAttribute("questionUserRelations");
				@SuppressWarnings("unchecked")
				ArrayList<QuestionAnswersRelation> questionAnswersRelations = (ArrayList<QuestionAnswersRelation>) request
		            .getAttribute("questionAnswersRelation");
				@SuppressWarnings("unchecked")
				ArrayList<Integer> loginUserBookmarks = (ArrayList<Integer>) request.getAttribute("loginUserBookmarks");
				@SuppressWarnings("unchecked")
				ArrayList<Category> categories= (ArrayList<Category>) request.getAttribute("categories");
			
      out.write("\r\n");
      out.write("\t\t\t");

			    User loginUser = (User) session.getAttribute(Constant.SCOPE_LOGIN_USER);
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"tablewrapper\">\r\n");
      out.write("\t\t\t<table class=\"list\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t<th>タイトル</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"ansNum\">回答<br>件数</th>\r\n");
      out.write("\t\t\t\t\t<th>本文</th>\r\n");
      out.write("\t\t\t\t\t<th>更新日</th>\r\n");
      out.write("\t\t\t\t");
 if (loginUser != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<th class=\"ansNum\">ブック<br>マーク</th>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>ユーザ</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

				    int cnt = 1;
				
      out.write("\r\n");
      out.write("\t\t\t\t");

				    for (QuestionUserRelation questionUserRelation : questionUserRelations) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(cnt);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
 CategoryDao categoryDao = new CategoryDao(); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span class=\"cate cateId");
      out.print(questionUserRelation.getQuestion().getCategoryId() );
      out.write('"');
      out.write('>');
      out.print(categoryDao.categoryName(questionUserRelation.getQuestion().getCategoryId()) );
      out.write("</span><br>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(Constant.PATH_DETAIL_QUE_ID);
      out.print(questionUserRelation.getQuestion().getId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(questionUserRelation.getQuestion().getTitle());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ansNum\">\r\n");
      out.write("\t\t\t\t\t");
 for (QuestionAnswersRelation questionAnswersRelation : questionAnswersRelations) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 if(questionUserRelation.getQuestion().getId()
						        == questionAnswersRelation.getQuestionUserRelation().getQuestion().getId()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( questionAnswersRelation.getAnswerUserRelation().size()  );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
 if (questionUserRelation.getQuestion().getContent().length() > 30) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(questionUserRelation.getQuestion().getContent().substring(0, 30));
      out.write("...\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(questionUserRelation.getQuestion().getContent());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"updatedAt\">");
      out.print(new SimpleDateFormat("yyyy/MM/dd HH:mm").format(questionUserRelation.getQuestion().getUpdatedOn()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t");
 if (loginUser != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<td class=\"ansNum bookmark\r\n");
      out.write("\t\t\t\t\t");
 if (loginUserBookmarks.size() != 0) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 for (int loginUserBookmark : loginUserBookmarks) {
							if (loginUserBookmark == questionUserRelation.getQuestion().getId()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tbookmark_on\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t \">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"");
      out.print(Constant.PATH_MYPAGE_CNTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_ACTION );
      out.write("\" value=\"");
      out.print(Constant.ACTION_USER_BOOKMARK);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_QUE_ID );
      out.write("\" value=\"");
      out.print(questionUserRelation.getQuestion().getId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" name=\"");
      out.print(Constant.ACTION_USER_BOOKMARK);
      out.write("\"><img src=\"./jsp/images/wisdom_icon_bookmark.png\" alt=\"ブックマークボタン\" width=\"24\" height=\"24\"></button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<td class=\"userName\">\r\n");
      out.write("\t\t\t\t\t");
 if (loginUser != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form action=\"");
      out.print(Constant.PATH_MYPAGE_CNTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_USER_ID);
      out.write("\" value=\"");
      out.print(questionUserRelation.getUser().getId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_USER_NAME);
      out.write("\" value=\"");
      out.print(questionUserRelation.getUser().getName());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"");
      out.print(questionUserRelation.getUser().getName());
      out.write("\" class=\"btn\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span class=\"btn\">");
      out.print(questionUserRelation.getUser().getName());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t");

					    cnt++;
					
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

				    }
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div><!-- .tablewrapper end -->\r\n");
      out.write("\t\t\t<div class=\"searchBlock\">\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(Constant.PATH_WISDOM_CNTL );
      out.write("\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_ACTION );
      out.write("\" value=\"");
      out.print(Constant.ACTION_SEARCH);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<p class=\"searchCategory\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"searchCategory\">カテゴリーで絞り込み</label><br>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"");
      out.print(Constant.PARAM_SEARCH_CATEGORY );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
 for (Category category : categories) {  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(category.getId());
      out.write('"');
      out.write('>');
      out.print(category.getName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"絞り込み\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(Constant.PATH_WISDOM_CNTL );
      out.write("\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_ACTION );
      out.write("\" value=\"");
      out.print(Constant.ACTION_SEARCH);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<p class=\"searchTitle\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"searchTitle\">タイトルで検索！</label><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"");
      out.print(Constant.PARAM_SEARCH_TITLE );
      out.write("\" required placeholder=\"ここに検索文字を入力\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"検索\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(Constant.PATH_WISDOM_CNTL );
      out.write("\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_ACTION );
      out.write("\" value=\"");
      out.print(Constant.ACTION_SEARCH);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<p class=\"searchUpdatedAt\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"searchUpdatedAt\">更新日で検索！</label><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"date\" name=\"");
      out.print(Constant.PARAM_SEARCH_UPDATEAT_BETWEEN );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t～\r\n");
      out.write("\t\t\t\t\t\t<input type=\"date\" name=\"");
      out.print(Constant.PARAM_SEARCH_UPDATEAT_AND );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"検索\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div><!-- .searchBlock end  -->\r\n");
      out.write("\t\t");
 if (loginUser != null) { 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"WisdomController?action=");
      out.print(Constant.ACTION_QUE_NEW);
      out.write("\" class=\"btn\">新規投稿</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(Constant.PATH_USER_CNTL);
      out.write("?action=");
      out.print(Constant.ACTION_USER_EDIT);
      out.write("\" class=\"btn\">ユーザー管理</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(Constant.PATH_MYPAGE_CNTL);
      out.write("\" class=\"btn\">マイページ</a>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t");
 if (loginUser != null) { 
      out.write("\r\n");
      out.write("\t\t<form action=\"");
      out.print(Constant.PATH_SESSION_CNTL );
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_ACTION );
      out.write("\" value=\"");
      out.print(Constant.ACTION_LOGOUT);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"LOGOUT\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t<form action=\"");
      out.print(Constant.PATH_SESSION_CNTL );
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_ACTION );
      out.write("\" value=\"");
      out.print(Constant.ACTION_VISITOR_LOGOUT);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"GO HOME\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t<small>\r\n");
      out.write("\t\t\t\t\tCopyright <script type=\"text/javascript\"> document.write(new Date().getFullYear()); </script> ZENET Co., Ltd. All Rights Reserved.\r\n");
      out.write("\t\t\t\t</small>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
