/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2021-02-23 14:11:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.User;
import util.Constant;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dto.User");
    _jspx_imports_classes.add("util.Constant");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>ログイン | Wisdom - Q＆A Communication</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=2.0,user-scalable=yes\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<link href=\"./jsp/wisdom.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script src=\"https://code.jquery.com/jquery-2.2.4.js\"></script>\r\n");
      out.write("\t\t<script src=\"./jsp/js/script.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body id=\"login\" class=\"sign\">\r\n");
      out.write("\t<div id=\"loading\"></div>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<p class=\"img logo\"><img src=\"./jsp/images/wisdom_logo.png\" alt=\"Wisdom - Q＆A Communication\"></p>\r\n");
      out.write("\t\t\t<div class=\"signbox\">\r\n");
      out.write("\t\t\t\t<h1>ログイン</h1>\r\n");
      out.write("\t\t\t\t");

					if (request.getAttribute(Constant.SCOPE_MSG_ERR) != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<p>");
      out.print(request.getAttribute(Constant.SCOPE_MSG_ERR));
      out.write("</p>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (request.getAttribute(Constant.SCOPE_MSG) != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<p>");
      out.print(request.getAttribute(Constant.SCOPE_MSG));
      out.write("</p>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(Constant.PATH_SESSION_CNTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(Constant.PARAM_ACTION);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(Constant.ACTION_LOGIN);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>登録E-mail</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"email\" name=\"");
      out.print(Constant.PARAM_LOGIN_EMAIL);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>パスワード</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"");
      out.print(Constant.PARAM_LOGIN_PASS);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"submit\" value=\"LOGIN\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<p class=\"rootBtn\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(Constant.PATH_USER_CNTL);
      out.write("\">ユーザ新規登録</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(Constant.PATH_SESSION_CNTL);
      out.write("\">ホームへ戻る</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div><!-- .signbox end -->\r\n");
      out.write("\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t<small>\r\n");
      out.write("\t\t\t\t\tCopyright <script type=\"text/javascript\"> document.write(new Date().getFullYear()); </script> ZENET Co., Ltd. All Rights Reserved.\r\n");
      out.write("\t\t\t\t</small>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
